spring.application.name=projeto
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_seguranca_info
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=local
logging.level.org.springframework.security=DEBUG

server.port=443

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=meu-cert

server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=1m